# Catppuccin themes for Spotify-player

[[themes]]
name = "Catppuccin-mocha"
[themes.palette]
background = "#1E1E2E"
foreground = "#C6D0F5"
black = "#1E1E2E"
blue = "#87B0F9"
cyan = "#89DCEB"
green = "#A6E3A1"
magenta = "#CBA6F7"
red = "#F38BA8"
white = "#C6D0F5"
yellow = "#F9E2AF"
bright_black = "#1E1E2E"
bright_blue = "#87B0F9"
bright_cyan = "#89DCEB"
bright_green = "#A6E3A1"
bright_magenta = "#CBA6F7"
bright_red = "#F38BA8"
bright_white = "#C6D0F5"
bright_yellow = "#F9E2AF"
selection_background = "#313244"
selection_foreground = "#C6D0F5"

[[themes]]
name = "Catppuccin-latte"
[themes.palette]
background = "#EFF1F5"
foreground = "#4C4F69"
black = "#EFF1F5"
blue = "#1E66F5"
cyan = "#04A5E5"
green = "#40A02B"
magenta = "#8839EF"
red = "#D20F39"
white = "#4C4F69"
yellow = "#DF8E1D"
bright_black = "#EFF1F5"
bright_blue = "#1E66F5"
bright_cyan = "#04A5E5"
bright_green = "#40A02B"
bright_magenta = "#8839EF"
bright_red = "#D20F39"
bright_white = "#4C4F69"
bright_yellow = "#DF8E1D"
selection_background = "#CCD0DA"
selection_foreground = "#4C4F69"

[[themes]]
name = "Catppuccin-frappe"
[themes.palette]
background = "#303446"
foreground = "#C6CEEF"
black = "#303446"
blue = "#8CAAEE"
cyan = "#89DCEB"
green = "#A6D189"
magenta = "#CA9EE6"
red = "#E78284"
white = "#C6CEEF"
yellow = "#E5C890"
bright_black = "#303446"
bright_blue = "#8CAAEE"
bright_cyan = "#89DCEB"
bright_green = "#A6D189"
bright_magenta = "#CA9EE6"
bright_red = "#E78284"
bright_white = "#C6CEEF"
bright_yellow = "#E5C890"
selection_background = "#414559"
selection_foreground = "#C6CEEF"

[[themes]]
name = "Catppuccin-macchiato"
[themes.palette]
background = "#24273A"
foreground = "#C5CFF5"
black = "#24273A"
blue = "#86AEF8"
cyan = "#91D7E3"
green = "#A6DA95"
magenta = "#C6A0F6"
red = "#ED8796"
white = "#C5CFF5"
yellow = "#EED49F"
bright_black = "#24273A"
bright_blue = "#86AEF8"
bright_cyan = "#91D7E3"
bright_green = "#A6DA95"
bright_magenta = "#C6A0F6"
bright_red = "#ED8796"
bright_white = "#C5CFF5"
bright_yellow = "#EED49F"
selection_background = "#363A4F"
selection_foreground = "#C5CFF5"
